// backend/src/db/dossier-seeds.ts
// Baseline seeds for Dossier v2 content entities (matching migration 0024)

import type {
  CancellationPolicyRecord,
  CompanyProfileRecord,
  DossierSignoffRecord,
  LocalSightseeingPackageRecord,
  MonumentRecord,
  PackageVehicleUpgradeRecord,
  PetTaxiPolicyRecord,
  TourPackageRecord,
  TransferRouteRecord,
} from "./dossier-types.js";

const BASE_TIME = "2026-10-04T00:00:00.000Z";

export const SEED_LOCAL_PACKAGES: LocalSightseeingPackageRecord[] = [
  {
    id: "30000000-0000-4000-a000-000000000001",
    packageCode: "agra-standard-sightseeing",
    name: "Agra Standard Sightseeing",
    durationHours: 8,
    includedKm: 80,
    covers: "Taj Mahal, Agra Fort, Mehtab Bagh, Itmad-Ud-Daulah (Baby Taj), Sadar Bazaar, Kinari Bazaar",
    parkingNote: "Monument entry fees & parking billed at actuals",
    fleetPrices: { sedan: 1900, ertiga: 2600, "innova-crysta": 2850, "tempo-traveller": 5500, urbania: 7500 },
    usePerKm: false,
    extraRates: {
      sedan: { per_km: 10, per_hr: 150 },
      ertiga: { per_km: 14, per_hr: 200 },
      "innova-crysta": { per_km: 18, per_hr: 250 },
      "tempo-traveller": { per_km: 25, per_hr: 400 },
      urbania: { per_km: 34, per_hr: 600 },
    },
    nightChargeInr: 0,
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "30000000-0000-4000-a000-000000000002",
    packageCode: "agra-extended-city-tour",
    name: "Agra Extended City Tour",
    durationHours: 12,
    includedKm: 120,
    covers: "Complete Agra heritage circuit including Fatehpur Sikri, Taj Mahal, and Agra Fort",
    parkingNote: "Monument entry fees & parking billed at actuals",
    fleetPrices: { sedan: 2200, ertiga: 2950, "innova-crysta": 3100, "tempo-traveller": 6500, urbania: 8500 },
    usePerKm: false,
    extraRates: {
      sedan: { per_km: 10, per_hr: 150 },
      ertiga: { per_km: 14, per_hr: 200 },
      "innova-crysta": { per_km: 18, per_hr: 250 },
      "tempo-traveller": { per_km: 25, per_hr: 400 },
      urbania: { per_km: 34, per_hr: 600 },
    },
    nightChargeInr: 0,
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
];

export const SEED_TRANSFER_ROUTES: TransferRouteRecord[] = [
  {
    id: "40000000-0000-4000-a000-000000000001",
    routeCode: "agc-station-drop",
    name: "Agra Cantt Railway Station (AGC) Drop/Pickup",
    distanceText: "~15–20 km",
    directionNote: "Doorstep pickup or drop at Agra Cantt Railway Station",
    fleetPrices: { sedan: 800, ertiga: 900, "innova-crysta": 1100, "tempo-traveller": 2200, urbania: 3500 },
    usePerKm: false,
    nightChargeInr: 0,
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "40000000-0000-4000-a000-000000000002",
    routeCode: "af-station-drop",
    name: "Agra Fort Railway Station (AF) Drop/Pickup",
    distanceText: "~12–15 km",
    directionNote: "Doorstep pickup or drop at Agra Fort Railway Station",
    fleetPrices: { sedan: 800, ertiga: 900, "innova-crysta": 1100, "tempo-traveller": 2200, urbania: 3500 },
    usePerKm: false,
    nightChargeInr: 0,
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "40000000-0000-4000-a000-000000000003",
    routeCode: "kheria-airport",
    name: "Agra Airport (Kheria AGR) Transfer",
    distanceText: "~15–25 km",
    directionNote: "Doorstep pickup or drop at Agra Kheria Airport",
    fleetPrices: { sedan: 900, ertiga: 1050, "innova-crysta": 1250, "tempo-traveller": 2400, urbania: 3800 },
    usePerKm: false,
    nightChargeInr: 0,
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "40000000-0000-4000-a000-000000000004",
    routeCode: "delhi-igi-oneway",
    name: "Delhi IGI Airport (DEL) Direct Transfer (One-Way)",
    distanceText: "225 km",
    directionNote: "Direct expressway express transfer between Agra and Delhi IGI Airport",
    fleetPrices: { sedan: 3499, ertiga: 4200, "innova-crysta": 5200, "tempo-traveller": 8500, urbania: 11500 },
    usePerKm: false,
    nightChargeInr: 0,
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
];

export const SEED_TOUR_PACKAGES: TourPackageRecord[] = [
  {
    id: "50000000-0000-4000-a000-000000000001",
    packageCode: "agra-sightseeing",
    name: "Same Day Agra Taj Mahal Tour",
    durationText: "1 Day",
    days: 1,
    nights: 0,
    baseTierCode: "sedan",
    startingPriceInr: 3499,
    fleetPrices: { sedan: 3499, ertiga: 4299, "innova-crysta": 5299, "tempo-traveller": 6999, urbania: 8999 },
    nightChargeInr: 300,
    inclusionsHighlight: "Taj Mahal & Agra Fort with dedicated guide & private AC car",
    inclusionsNote: null,
    imageUrl: "/assets/packages/taj-dawn.webp",
    gallery: [
      { url: "/assets/places/gallery/taj-mahal-01.jpg", caption: "Iconic reflection pool at golden dawn", alt: "Taj Mahal reflection pool at dawn in Agra" },
      { url: "/assets/places/gallery/agra-fort-01.jpg", caption: "Grand Amar Singh Gate at Agra Red Fort", alt: "Agra Fort red sandstone entrance gate" },
      { url: "/assets/places/gallery/mehtab-bagh-01.jpg", caption: "Sunset vantage point over Yamuna", alt: "Mehtab Bagh sunset over Taj Mahal" },
      { url: "/assets/places/gallery/taj-mahal-02.jpg", caption: "Intricate marble archways & minarets", alt: "Taj Mahal minarets and dome details" },
    ],
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "50000000-0000-4000-a000-000000000002",
    packageCode: "taj-mahal-sunrise-tour",
    name: "Taj Mahal Sunrise Tour",
    durationText: "1 Day",
    days: 1,
    nights: 0,
    baseTierCode: "sedan",
    startingPriceInr: 12999,
    fleetPrices: { sedan: 12999, ertiga: 13799, "innova-crysta": 14799, "tempo-traveller": 16499, urbania: 18499 },
    nightChargeInr: 300,
    inclusionsHighlight: "Sunrise VIP entry, Mehtab Bagh & breakfast at 5-star hotel",
    inclusionsNote: null,
    imageUrl: "/assets/packages/taj-dawn.webp",
    gallery: [
      { url: "/assets/places/gallery/taj-mahal-02.jpg", caption: "Dawn glow across ivory marble", alt: "Taj Mahal at sunrise" },
      { url: "/assets/places/gallery/mehtab-bagh-02.jpg", caption: "Reflections from Charbagh gardens", alt: "Mehtab Bagh sunrise view" },
      { url: "/assets/places/gallery/taj-mahal-03.jpg", caption: "Intricate pietra dura floral inlays", alt: "Pietra dura marble inlay details" },
    ],
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "50000000-0000-4000-a000-000000000003",
    packageCode: "mathura-vrindavan",
    name: "Mathura & Vrindavan Darshan",
    durationText: "1 Day",
    days: 1,
    nights: 0,
    baseTierCode: "sedan",
    startingPriceInr: 4200,
    fleetPrices: { sedan: 4200, ertiga: 5000, "innova-crysta": 6000, "tempo-traveller": 7700, urbania: 9700 },
    nightChargeInr: 300,
    inclusionsHighlight: "Krishna Janmabhoomi, Banke Bihari, Prem Mandir & evening Aarti",
    inclusionsNote: null,
    imageUrl: "/assets/packages/mathura.webp",
    gallery: [
      { url: "/assets/places/gallery/mathura-vrindavan-01.jpg", caption: "Banke Bihari & Prem Mandir illumination", alt: "Prem Mandir illuminated at night" },
      { url: "/assets/places/gallery/mathura-vrindavan-02.jpg", caption: "Sacred Yamuna Ghats at sunset", alt: "Yamuna river ghats Mathura" },
      { url: "/assets/places/gallery/mathura-vrindavan-03.jpg", caption: "Evening aarti ceremony at Vrindavan", alt: "Evening temple ceremony Vrindavan" },
    ],
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "50000000-0000-4000-a000-000000000004",
    packageCode: "gatimaan-express-agra-tour",
    name: "Same Day Agra by Gatimaan Train",
    durationText: "1 Day",
    days: 1,
    nights: 0,
    baseTierCode: "sedan",
    startingPriceInr: 14999,
    fleetPrices: { sedan: 14999, ertiga: 15799, "innova-crysta": 16799, "tempo-traveller": 18499, urbania: 20499 },
    nightChargeInr: 300,
    inclusionsHighlight: "Return Gatimaan train tickets, luxury station transfers & monument access",
    inclusionsNote: null,
    imageUrl: "/assets/packages/agra-fort.webp",
    gallery: [
      { url: "/assets/places/gallery/agra-fort-02.jpg", caption: "Diwan-i-Khas marble pavilion", alt: "Diwan-i-Khas inside Agra Fort" },
      { url: "/assets/places/gallery/taj-mahal-01.jpg", caption: "Taj Mahal express afternoon visit", alt: "Taj Mahal" },
    ],
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "50000000-0000-4000-a000-000000000005",
    packageCode: "agra-unhurried",
    name: "Agra Overnight Experience",
    durationText: "2 Days / 1 Night",
    days: 2,
    nights: 1,
    baseTierCode: "sedan",
    startingPriceInr: 7800,
    fleetPrices: { sedan: 7800, ertiga: 8600, "innova-crysta": 9600, "tempo-traveller": 11300, urbania: 13300 },
    nightChargeInr: 300,
    inclusionsHighlight: "Sunset at Mehtab Bagh, Sunrise at Taj Mahal, Baby Taj & Fatehpur Sikri",
    inclusionsNote: null,
    imageUrl: "/assets/packages/agra-fort.webp",
    gallery: [
      { url: "/assets/places/gallery/agra-fort-03.jpg", caption: "Mughal courtyards & archways", alt: "Agra Fort royal courtyard" },
      { url: "/assets/places/gallery/fatehpur-sikri-01.jpg", caption: "Buland Darwaza imperial gate", alt: "Buland Darwaza at Fatehpur Sikri" },
      { url: "/assets/places/gallery/fatehpur-sikri-02.jpg", caption: "Panch Mahal royal pavilion", alt: "Panch Mahal palace" },
    ],
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "50000000-0000-4000-a000-000000000006",
    packageCode: "golden-triangle",
    name: "Golden Triangle Tour",
    durationText: "3 Days / 2 Nights",
    days: 3,
    nights: 2,
    baseTierCode: "sedan",
    startingPriceInr: 18500,
    fleetPrices: { sedan: 18500, ertiga: 19300, "innova-crysta": 20300, "tempo-traveller": 22000, urbania: 24000 },
    nightChargeInr: 300,
    inclusionsHighlight: "Delhi, Agra & Jaipur circuit with highway tolls and chauffeur accommodation",
    inclusionsNote: null,
    imageUrl: "/assets/packages/golden-triangle.webp",
    gallery: [
      { url: "/assets/places/gallery/jaipur-pink-city-01.jpg", caption: "Hawa Mahal (Palace of Winds)", alt: "Hawa Mahal facade Jaipur" },
      { url: "/assets/places/gallery/taj-mahal-01.jpg", caption: "Agra Taj Mahal sunrise visit", alt: "Taj Mahal Agra" },
      { url: "/assets/places/gallery/jaipur-pink-city-02.jpg", caption: "Amber Fort hilltop ramparts", alt: "Amber Fort Jaipur" },
    ],
    status: "draft",
    isActive: true,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
];

export const SEED_PACKAGE_UPGRADES: PackageVehicleUpgradeRecord[] = [
  {
    id: "60000000-0000-4000-a000-000000000001",
    packageId: null,
    tierCode: "ertiga",
    passengerNote: "Up to 6 Passengers",
    surchargeInr: 800,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "60000000-0000-4000-a000-000000000002",
    packageId: null,
    tierCode: "innova-crysta",
    passengerNote: "VIP Executive Comfort (6–7 Passengers)",
    surchargeInr: 1800,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "60000000-0000-4000-a000-000000000003",
    packageId: null,
    tierCode: "tempo-traveller",
    passengerNote: "Large Family / Group (12–16 Passengers)",
    surchargeInr: 3500,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "60000000-0000-4000-a000-000000000004",
    packageId: null,
    tierCode: "urbania",
    passengerNote: "Ultra-Luxury Luxury Van (10–17 Passengers)",
    surchargeInr: 5500,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
];

export const SEED_CANCELLATION_POLICIES: CancellationPolicyRecord[] = [
  {
    id: "70000000-0000-4000-a000-000000000001",
    policyType: "cab",
    noticePeriodText: "24+ hours before departure",
    sortOrder: 1,
    feeRetainedPercent: 0,
    refundPercent: 100,
    ruleText: "Full refund, no questions asked.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000002",
    policyType: "cab",
    noticePeriodText: "<24 hours before departure",
    sortOrder: 2,
    feeRetainedPercent: 100,
    refundPercent: 0,
    ruleText: "Advance retained to compensate driver and vehicle allocation.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000003",
    policyType: "cab",
    noticePeriodText: "No-show / Driver arrival dispatch",
    sortOrder: 3,
    feeRetainedPercent: 100,
    refundPercent: 0,
    ruleText: "Advance forfeited.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000004",
    policyType: "tour_package",
    noticePeriodText: "61+ days prior to departure",
    sortOrder: 10,
    feeRetainedPercent: 0,
    refundPercent: 100,
    ruleText: "Full refund minus payment gateway transaction fee.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000005",
    policyType: "tour_package",
    noticePeriodText: "46–60 days prior to departure",
    sortOrder: 11,
    feeRetainedPercent: 10,
    refundPercent: 90,
    ruleText: "10% cancellation charge.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000006",
    policyType: "tour_package",
    noticePeriodText: "31–45 days prior to departure",
    sortOrder: 12,
    feeRetainedPercent: 20,
    refundPercent: 80,
    ruleText: "20% cancellation charge.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000007",
    policyType: "tour_package",
    noticePeriodText: "16–30 days prior to departure",
    sortOrder: 13,
    feeRetainedPercent: 30,
    refundPercent: 70,
    ruleText: "30% cancellation charge.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000008",
    policyType: "tour_package",
    noticePeriodText: "6–15 days prior to departure",
    sortOrder: 14,
    feeRetainedPercent: 55,
    refundPercent: 45,
    ruleText: "55% cancellation charge.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "70000000-0000-4000-a000-000000000009",
    policyType: "tour_package",
    noticePeriodText: "0–5 days / No-show",
    sortOrder: 15,
    feeRetainedPercent: 100,
    refundPercent: 0,
    ruleText: "No refund applicable.",
    refundTimelineNote: "5–7 business days to original bank/UPI",
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
];

export const SEED_COMPANY_PROFILE: CompanyProfileRecord = {
  id: "80000000-0000-4000-a000-000000000001",
  brandName: "SK Baghel Tour & Travels",
  officeAddress: "Taj Ganj, Agra, Uttar Pradesh 282001",
  primaryPhone: "+91 97628 17598",
  whatsappNumber: "+91 97628 17598",
  email: "[TBD — confirm with client]",
  gstin: "[TBD — confirm with client]",
  operatingHours: "Bookings Open 24×7, 365 Days",
  mapsLocation: "https://maps.google.com/?q=Agra",
  dossierVersion: "1.0",
  dossierStatus: "pending_review",
  createdAt: BASE_TIME,
  updatedAt: BASE_TIME,
};

export const SEED_DOSSIER_SIGNOFFS: DossierSignoffRecord[] = [
  { id: "90000000-0000-4000-a000-000000000001", sectionKey: "fleet_rates", sectionTitle: "Fleet Specifications & Base Per-KM Rates", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000002", sectionKey: "local_transfers", sectionTitle: "Local Sightseeing & Airport/Railway Transfers", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000003", sectionKey: "one_way_routes", sectionTitle: "Intercity One-Way Expressway Corridors", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000004", sectionKey: "outstation_rules", sectionTitle: "Outstation Round-Trip Rules & Daily Benchmarks", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000005", sectionKey: "night_allowance", sectionTitle: "Driver Night Allowance Window & Charges", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000006", sectionKey: "advance_deposit", sectionTitle: "28% Advance Deposit Booking Formula", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000007", sectionKey: "coupon", sectionTitle: "Promotional Coupon ASTTCAR500OFF", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000008", sectionKey: "tour_packages", sectionTitle: "Signature Tour Packages & Pricing", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000009", sectionKey: "cancellation", sectionTitle: "Cancellation & Refund Tier Schedules", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "90000000-0000-4000-a000-000000000010", sectionKey: "specialized_offerings", sectionTitle: "Monument Operating Protocols & Heritage Guidelines", status: "pending", clientNotes: null, approvedBy: null, approvedAt: null, createdAt: BASE_TIME, updatedAt: BASE_TIME },
];

export const SEED_MONUMENTS: MonumentRecord[] = [
  { id: "a0000000-0000-4000-a000-000000000001", name: "Taj Mahal", visitingHours: "06:00 – 18:30 (Sunrise to Sunset)", closedNote: "Closed on Fridays", historicalContext: "Crown jewel of Mughal architecture, UNESCO World Heritage site built by Shah Jahan.", sortOrder: 1, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000002", name: "Agra Red Fort", visitingHours: "06:00 – 18:00", closedNote: "Open all days", historicalContext: "Main residence of the emperors of the Mughal Dynasty until 1638.", sortOrder: 2, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000003", name: "Fatehpur Sikri", visitingHours: "06:00 – 18:00", closedNote: "Open all days", historicalContext: "Imperial red sandstone city founded by Emperor Akbar in 1571.", sortOrder: 3, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000004", name: "Itmad-Ud-Daulah (Baby Taj)", visitingHours: "08:00 – 00:00 (Midnight)", closedNote: "Open all days", historicalContext: "Tomb of Mirza Ghiyas Beg, precursor to the Taj Mahal with intricate pietra dura inlay.", sortOrder: 4, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000005", name: "Mehtab Bagh", visitingHours: "06:00 – 21:00", closedNote: "Open all days", historicalContext: "Moonlight garden providing sunset views of the Taj Mahal across the Yamuna River.", sortOrder: 5, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000006", name: "Sikandra (Akbar Tomb)", visitingHours: "08:00 – 18:00", closedNote: "Open all days", historicalContext: "Final resting place of Mughal Emperor Akbar, blending Islamic, Hindu, and Buddhist motifs.", sortOrder: 6, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000007", name: "Jama Masjid Agra", visitingHours: "08:00 – 18:00", closedNote: "Open all days (Prayer hours restricted)", historicalContext: "Opposite Agra Fort, built by Jahanara Begum in 1648.", sortOrder: 7, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000008", name: "Moti Masjid (Pearl Mosque)", visitingHours: "06:00 – 18:00", closedNote: "Inside Agra Fort", historicalContext: "Lustrous white marble mosque commissioned by Shah Jahan.", sortOrder: 8, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000009", name: "Jodha Bai Ka Rauza", visitingHours: "10:00 – 19:00", closedNote: "Open all days", historicalContext: "Largest residential palace complex inside Fatehpur Sikri.", sortOrder: 9, createdAt: BASE_TIME, updatedAt: BASE_TIME },
  { id: "a0000000-0000-4000-a000-000000000010", name: "Mariam-Uz-Zamani Palace", visitingHours: "10:00 – 19:00", closedNote: "Open all days", historicalContext: "Palace dedicated to Akbar Portuguese-Christian / Rajput consort.", sortOrder: 10, createdAt: BASE_TIME, updatedAt: BASE_TIME },
];

export const SEED_PET_POLICY: PetTaxiPolicyRecord = {
  id: "b0000000-0000-4000-a000-000000000001",
  isOffered: false,
  seatProtectionNote: "Not applicable — pet taxi service discontinued per client policy.",
  breedRestrictionNote: "Pets and animals are not permitted inside vehicles.",
  comfortStopNote: "Standard comfort and hydration stops provided for human passengers.",
  bookingInstruction: "Pets are strictly not permitted in vehicles to maintain passenger hygiene.",
  createdAt: BASE_TIME,
  updatedAt: BASE_TIME,
};
